name: grizzly_scales
description: Provides scales and interpolators for grizzly_viz
version: 0.0.2-dev
homepage:
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:

dev_dependencies:
  test: ^0.12.0
